
version: 2

models:
    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: REGION
            description: "The primary key for this table"
            tests:
                - not_null
    - name: newData
      description: "A starter dbt model"
      columns:
          - name: REGION
            description: "The primary key for this table"
            tests:
                - not_null